### ISSUE TITLE
Deployoing to heroku syntex error

### ISSUE THREAD

**Issue by techverx** [twilio/voice-quickstart-server-python#15] opened 2017-06-21 16:50 UTC
`-----> Python app detected

-----> Installing python-3.6.1

-----> Installing pip

-----> Installing requirements with pip

       Collecting Flask==0.10.1 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 1))

         Downloading Flask-0.10.1.tar.gz (544kB)

       Collecting Jinja2==2.7.3 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 2))

         Downloading Jinja2-2.7.3.tar.gz (378kB)

       Collecting MarkupSafe==0.23 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 3))

         Downloading MarkupSafe-0.23.tar.gz

       Collecting Werkzeug==0.9.6 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 4))

         Downloading Werkzeug-0.9.6.tar.gz (1.1MB)

       Collecting httplib2==0.9 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 5))

         Downloading httplib2-0.9.zip (209kB)

       Collecting itsdangerous==0.24 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 6))

         Downloading itsdangerous-0.24.tar.gz (46kB)

       Collecting six==1.* (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 7))

         Downloading six-1.10.0-py2.py3-none-any.whl

       Collecting twilio==6.0rc11 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 8))

         Downloading twilio-6.0.0rc11-py2.py3-none-any.whl (694kB)

       Collecting wsgiref==0.1.2 (from -r /tmp/build_8cf1934d10e9f2a2df5832b6aa2097d9/twilio-voice-quickstart-server-python-892d53b/requirements.txt (line 9))

         Downloading wsgiref-0.1.2.zip

           Complete output from command python setup.py egg_info:

           Traceback (most recent call last):

             File "<string>", line 1, in <module>

             File "/tmp/pip-build-w7o6yng2/wsgiref/setup.py", line 5, in <module>

               import ez_setup

             File "/tmp/pip-build-w7o6yng2/wsgiref/ez_setup/__init__.py", line 170

               print "Setuptools version",version,"or greater has been installed."

                                        ^

           SyntaxError: Missing parentheses in call to 'print'

           

           ----------------------------------------

       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w7o6yng2/wsgiref/

 !     Push rejected, failed to compile Python app.

 !     Push failed`

**Comment by bchen-twilio** [comment] 2017-06-21 17:51
Hi @techverx 

Thanks for reporting the issue.
It seems the issue is caused due to the compatibility between `wsgiref` and python3, which is currently used in Heroku's instances. To ensure the backward compatibility with python2, unfortunately we cannot just remove the `wsgireg` lib from the requirements.txt now, but I've tried deploying without it and was able to finish the installation and able to hit the `/accessToken` endpoint.

Please let us know if this helps.

-bobie

**Comment by techverx** [comment] 2017-06-22 08:11
Hi @bchen-twilio 
Thanks a lot

**Comment by bchen-twilio** [comment] 2017-06-22 16:52
You are welcome @techverx.
I'll close this ticket but do feel free to open new ticket if you run into any issue in the future.
Looking forward to your awesome Voice/Twilio apps!

-bobie

**Closed by bchen-twilio** 2017-06-22 16:52 UTC
